# Basic
title: 化风
subtitle: 沉稳 大气 笃行 克己
description: 欢迎访问我的个人博客~
# 头像里面的标题
avatarTitle: 化 风
# 头像里面的描述
avatarDesc: 前端 / PHP 攻城狮
url: "http://xinchanghao.github.io"

# Comment
comment:
    disqus: huafeng

# Social
social:
    #weibo: 5366874726
    github: xinchanghao
    twitter: xinchanghao
    mail: chh.xin@gmail.com

# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: 46b9471b9f2035075f2e22f64055d7ab

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-118703487-1
    host: auto


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/xinchanghao/xinchanghao.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: article, description: archive, url: '/archive'}
    - {title: tag, description: tags, url: '/tags'}
    - {title: aboutme, description: about, url: '/aboutme'}
    #- {title: 关于我, description: about, url: '/about'}
    #- {title: 开发区, description: tinyHeart, url: '/tinyHeart'}
    - {title: leetcode, description: LeetCode, url: '/leetcode'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"
